### ISSUE TITLE
Use the input's label by default. Create option for this instead of 3-4 different checks

### ISSUE THREAD

**Issue by AaronJWhite** [vmichnowicz/jquery.formvalidate#5]
Hello,
First off, I am sorry if this is not the proper way to submit a feature request.

Request:
It's very common for form inputs to have a corresponding <label> tag containing the input's title that an end user would understand. I think when messages are enabled the plugin should first look to see if the input has a label and use that text. 
The jquery selector would be something like: $('label[for="'+ inputId +'"]')

Also, if this is not the default it would be nice if there is an option to enable this.

Great work on the plugin!

**Comment by vmichnowicz** [comment]
Thats a good idea, I'll try and work that into the plugin.

**Comment by vmichnowicz** [comment]
Just created new branch [title-from-labels](https://github.com/vmichnowicz/jquery.formvalidate/tree/title-from-labels) does this seem to do what you were talking about?

**Comment by AaronJWhite** [comment]
Yeah. Lines 318-321 are pretty much what I was looking for.  Thanks for adding it! Would it be beneficial to make that section an option instead of all of the "guess" checks?

**Comment by vmichnowicz** [comment]
Cool, glad you like it. I'll get that merged into master soon. I'm not sure requiring an an option would be the best approach. I think most uses want the module to magically "just work". I could see some use cases for disabling the fancy title-determining processes though...
